name: Deploy to Demo Server

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Upload artifact via SCP
        run: |
          scp -i ~/.ssh/deploy_key -r ./target/job-winner-0.0.1-SNAPSHOT.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/opc

      - name: Restart Application
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          pkill -f 'java -Dspring.profiles.active=demo'
          sleep 2
          nohup java -Dspring.profiles.active=demo -Dui.path=http://{{ secrets.REMOTE_HOST }} -jar job-winner-0.0.1-SNAPSHOT.jar > job-winner-output.log 2>&1 &
          echo $! > job-winner.pid
          EOF
